name: End-to-end tests with Docker image on Chrome
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    container:
      image: cypress/browsers:node18.12.0-chrome103-ff107
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: node -v

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          browser: chrome

      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
