name: End-to-end tests with Docker image on Chrome
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        container:
          [
            cypress/browsers:node14.17.6-chrome100-ff98,
            cypress/browsers:node16.18.0-chrome90-ff88,
            cypress/browsers:node18.12.0-chrome103-ff107,
          ]
        
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          browser: firefox
