name: End-to-end tests with Docker image on Chrome
on: 
  push:
    branches:
     - main
jobs:
  cypress-run-docker-node-14-19-0:
    runs-on: ubuntu-20.04
    container:
      image: cypress/browsers:node14.19.0-chrome100-ff99-edge
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies, cache them and run all Cypress tests
        uses: cypress-io/github-action@v4
        with:
          browser: chrome

  cypress-run-docker-node-16-18-0:
    runs-on: ubuntu-20.04
    container:
      image: cypress/browsers:node16.18.0-chrome90-ff88
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies, cache them and run all Cypress tests
        uses: cypress-io/github-action@v4
        with:
          browser: chrome

  cypress-run-docker-node18-12-0:
    runs-on: ubuntu-20.04
    container:
      image: cypress/browsers:node18.12.0-chrome103-ff107
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies, cache them and run all Cypress tests
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
